# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 10:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GITComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_comment_id', models.IntegerField()),
                ('comment_message', models.CharField(max_length=500)),
                ('comment_url', models.CharField(max_length=500)),
                ('repository', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField()),
                ('rating', models.IntegerField(default=10)),
                ('commented_by', models.ForeignKey(blank=True, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GITCommits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_id', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField()),
                ('commit_message', models.CharField(max_length=500)),
                ('repository', models.CharField(blank=True, max_length=500)),
                ('committed_by', models.ForeignKey(blank=True, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gitcomments',
            name='commit',
            field=models.ForeignKey(blank=True, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, to='gitapp.GITCommits'),
        ),
    ]
